spring:
  application:
    name: co-mu-nity
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update  # 기존 데이터베이스를 유지하면서 스키마를 업데이트
    show-sql: true      # SQL 쿼리 출력 활성화
    properties:
      hibernate:
        format_sql: true   # 쿼리를 보기 좋게 출력


